name: Terraform CI/CD Demo

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        env:
          TF_VAR_target_host: 10.161.120.45
          TF_VAR_ssh_user: admino
          TF_VAR_private_key_path: /home/admino/.ssh/id_ed25519
        run: terraform apply -auto-approve

