name: First Terraform CI/CD Lab

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: terraform-hosted   # Uses your local runner VM
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Apply Terraform
        run: terraform apply -auto-approve
